version: 2
jobs:
  build:
    working_directory: ~/pulverized
    docker:
      - image: objectifiedjs/objectified-docker-images:10-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm test
